### ISSUE TITLE
build fail: 'c++17' is not defined for option 'std'

### ISSUE THREAD

**Issue by ldoublewood** [no-fee-ethereum-mining/nsfminer#72]
**Describe the bug**
build fail: 'c++17' is not defined for option 'std'
**To Reproduce**
1. checkout v1.3.3
2. mkdir build
3. cd build
4. cmake ..
5. cmake --build .
**Expected behavior**
build succeed
**Screenshots (Optional)**

**Environment (please complete the following information):**
- Operating System: [e.g. Windows 10]
Ubuntu 20.04
- Hardware [e.g. GTX 1070]
RTX 2080ti
- Ethminer Version [e.g. 0.14]
- Ethminer options used

**Additional context**
[  0%] Built target nsfminer-buildinfo-git
[  9%] Built target nsfminer-buildinfo
[ 24%] Built target dev
[ 39%] Built target hwmon
[ 42%] Building NVCC (Device) object libcuda/CMakeFiles/cuda.dir/cuda_generated_ethash_cuda_miner_kernel.cu.o
nvcc fatal   : Value 'c++17' is not defined for option 'std'
CMake Error at cuda_generated_ethash_cuda_miner_kernel.cu.o.Release.cmake:220 (message):
  Error generating
  /root/src/nsfminer/build/libcuda/CMakeFiles/cuda.dir//./cuda_generated_ethash_cuda_miner_kernel.cu.o

make[2]: *** [libcuda/CMakeFiles/cuda.dir/build.make:65: libcuda/CMakeFiles/cuda.dir/cuda_generated_ethash_cuda_miner_kernel.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:462: libcuda/CMakeFiles/cuda.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by xgnom666x** [comment]
need to upgrade g++/gcc compiler versions.

**Comment by jean-m-cyr** [comment]
You need a more recent version of CUDA, 11 or better to be precise.

**Comment by taomanwai** [comment]
I 'm using CUDA 11.2 and g++/gcc 9 , but still get the same error, any solutions?

**Comment by DeanIsMe** [comment]
If CUDA 11 is required, could you please update the build instructions? They currently say that CUDA >=9.0 is required.
https://github.com/no-fee-ethereum-mining/nsfminer/blob/master/docs/BUILD.md

**Comment by mmmeeeker** [comment]
> I 'm using CUDA 11.2 and g++/gcc 9 , but still get the same error, any solutions?

I'm using CUDA 11.3 and gcc 9.3.0 on Ubuntu 20.04.2. Getting this as well.

**Comment by r5574** [comment]
I'm using CUDA 11.2 with gcc 9.3.0 on Ubuntu 20.04 Server and have the same issue.

**Comment by mmmeeeker** [comment]
I know absolutely nothing about how these things are architected, but I suppose it's about time. Hoping I'll have some time later this upcoming week to take a look. Obviously, will post if I come across something.

**Comment by Ryan-pelo** [comment]
I'm using CUDA 11.3 and gcc 9.3.0 on Ubuntu 20.04 LTS and have the same issue

**Comment by dipteshkanojia** [comment]
I'm using CUDA 11.3 and gcc 9.3.0 on Ubuntu 20.04 LTS. Facing the same issue. Could you please help?
Thanks in advance.

**Comment by hunteros95** [comment]
I’m also having this error. Running CUDA 11.3, gcc 9.3.0, and Ubuntu 20.04. Local rig with 3 3070s and 3 3080s.

**Comment by camhr** [comment]
Same issue here.

**Comment by dorienh** [comment]
Same issue. Ubuntu fresh install with nvidia 3090 with latest drivers

**Comment by mmmeeeker** [comment]
Hi all, this is not much of a fix. Since my earlier comment, I've switched over to Gentoo, and, for whatever reason, this has become a non-issue for me on fresh install. It may be something particular to Ubuntu, but that doesn't seem too, too likely. I used genkernel and haven't installed too many packages besides those necessary for i3/ generic ricing items like neofetch, Java, Python, and Brave Browser... (C/C++ things are part of GNU of course).

gcc -- 10.3.0 via gcc --version
cmake -- 3.18.5 via cmake --version
CUDA -- 11.21.152 via nvcc --version
Kernel is at 5.10.27 via neofetch. Like I said, running Gentoo, not Ubuntu, but am very much not sure what sort of difference this would make.

After having spent much more time with C/C++ over the past month, the things that immediately come to mind are the compiler versions and the standards. Perhaps try specifying C++20? Could be worth a shot.

Beyond that, I would assume that there's a chance that Ubuntu uses nouveau rather than the prop nvidia drivers, which I realized were causing several issues on my install (albeit, this was causing issues for me long before I touched installing this, so I really do not know; in particular, nouveau does not support 3000 series -- am currently running one 3090 in my workstation). Not sure what the interaction would be with just installing CUDA based off of that (in particular, would you be able to successfully "install" CUDA while still running nouveau? I have a hunch that's the case but have little experience in that vertical, if you will).
